### ISSUE TITLE
Wrapping preventing jobsQueue from detecting async functions

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-newrelic#14]
### Expected behavior
I'm not sure how this should work, but probably it shouldn't modify existing behavior in such a way.
### Actual behavior
It's wrapping functions passed to `jobsQueue`:
```
New job registered: broadcasterReleaseQueue, isAsync: false, type: function wrappedJob(cb) {
				newrelic.startBackgroundTransaction(name, 'jobQueue', () => {
					const transaction = newrelic.getTransaction();
					originalJob.call(this, () => {
						transaction.end();
						cb.call(this);
					});
				});
			}
```
so making this check to fail:
https://github.com/LiskHQ/lisk-sdk/blob/4ac6c58536c1b52883ed9c528bda1794b4fc1463/framework/src/modules/chain/helpers/jobs_queue.js#L68-L70
### Steps to reproduce
Add:
```
console.log(`New job registered: ${name}, isAsync: ${util.types.isAsyncFunction(job)}, type: ${job}`);
```
here:
https://github.com/LiskHQ/lisk-sdk/blob/4ac6c58536c1b52883ed9c528bda1794b4fc1463/framework/src/modules/chain/helpers/jobs_queue.js#L48
Enable New Relic, run the node.
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.2`

**Comment by nazarhussain** [comment]
For other's reference if you set the `DEBUG=newrelic:lisk*` while starting the app, you can see a lot of helpful debugging information.
