### ISSUE TITLE
Please use LTS version of node

### ISSUE THREAD

**Issue by magick93** [LiskHQ/lisk-newrelic#16]
### Expected behavior

Expect to be able to build lisk in an environment that has a policy of using LTS node versions.

### Actual behavior

Unable to build.

```

npm info it worked if it ends with ok
--
  | npm info using npm@6.9.0
  | npm info using node@v10.16.0
  | npm info lifecycle lisk-core@2.0.0-rc.0~preinstall: lisk-core@2.0.0-rc.0
  | npm timing stage:loadCurrentTree Completed in 11ms
  | npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
  | npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1010ms
  | npm http fetch GET 200 https://registry.npmjs.org/axios  521ms
  | npm http fetch GET 200 https://registry.npmjs.org/is-buffer  36ms
  | npm info lifecycle lisk-newrelic@0.1.0~prepack: lisk-newrelic@0.1.0
  | npm info lifecycle lisk-newrelic@0.1.0~postpack: lisk-newrelic@0.1.0
  | npm timing stage:rollbackFailedOptional Completed in 0ms
  | npm timing stage:runTopLevelLifecycles Completed in 4567ms
  | npm ERR! code ENOTSUP
  | npm ERR! notsup Unsupported engine for lisk-newrelic@0.1.0: wanted: {"node":"10.15.3","npm":"6.4.1"} (current: {"node":"10.16.0","npm":"6.9.0"})
  | npm ERR! notsup Not compatible with your version of node/npm: lisk-newrelic@0.1.0
  | npm ERR! notsup Not compatible with your version of node/npm: lisk-newrelic@0.1.0
  | npm ERR! notsup Required: {"node":"10.15.3","npm":"6.4.1"}
  | npm ERR! notsup Actual:   {"npm":"6.9.0","node":"10.16.0"}
  | npm timing npm Completed in 5421ms


```

### Steps to reproduce

Try building with a where a LTS version is required, eg, using node s2i ( eg https://github.com/nodeshift/centos7-s2i-nodejs or https://github.com/sclorg/s2i-nodejs-container/tree/master/10) .

I have the same issue in the Lisq-core project (see https://github.com/LiskHQ/lisk-core/issues/79). 

# Questions

I can see that `newrelic-lisk` is used at https://github.com/LiskHQ/lisk-sdk/blob/942d320795d13cf0ad83e33d8e78c07357ae8700/framework/src/modules/chain/utils/newrelic_lisk.js#L20 but cannot see where, in which `package.json` file this module is specified. 

- How does it get loaded into the project?
- Which project uses `lisk-newrelic`?

**Comment by shuse2** [comment]
I have updated to allow the range.
For the question, it's used in `lisk-framework` and dynamically .
